/* Liste des icônes ng-zorro, partagée entre le point d'entrée standalone et embarqué pour ne jamais diverger. */
import {
  AimOutline, AlignLeftOutline, ApartmentOutline, AppstoreOutline, ArrowDownOutline, ArrowLeftOutline, ArrowRightOutline,
  BarChartOutline, BellOutline, BugOutline, BulbOutline,
  BranchesOutline, CalendarOutline, CalculatorOutline, CaretDownOutline, CheckOutline, CheckCircleOutline,
  ClockCircleOutline, CloseCircleOutline, ClusterOutline, CodeOutline,
  CopyOutline, DashboardOutline, DatabaseOutline, DeleteOutline, DeploymentUnitOutline, DownloadOutline,
  EditOutline, ExperimentOutline, ExportOutline, EyeOutline, EyeInvisibleOutline,
  FieldNumberOutline, FileTextOutline, FilterOutline, FolderOutline,
  HistoryOutline, HolderOutline, ImportOutline, InfoCircleOutline, InfoOutline,
  LeftOutline, LineChartOutline, LinkOutline, LockOutline, LogoutOutline,
  MergeCellsOutline, MoreOutline, NodeExpandOutline, PercentageOutline, PlayCircleOutline, PlusOutline,
  QrcodeOutline, QuestionCircleOutline, ReloadOutline, RightOutline,
  SafetyCertificateOutline, SafetyCertificateFill, SaveOutline, ScissorOutline, SearchOutline,
  SettingOutline, SettingTwoTone,
  TableOutline, TagOutline, TeamOutline, ToolOutline, TrophyOutline,
  UploadOutline, UserOutline, UserAddOutline, WarningOutline,
} from '@ant-design/icons-angular/icons';

export const NZ_ICONS_LIST = [
  AimOutline, AlignLeftOutline, ApartmentOutline, AppstoreOutline, ArrowDownOutline, ArrowLeftOutline, ArrowRightOutline,
  BarChartOutline, BellOutline, BugOutline, BulbOutline,
  BranchesOutline, CalendarOutline, CalculatorOutline, CaretDownOutline, CheckOutline, CheckCircleOutline,
  ClockCircleOutline, CloseCircleOutline, ClusterOutline, CodeOutline,
  CopyOutline, DashboardOutline, DatabaseOutline, DeleteOutline, DeploymentUnitOutline, DownloadOutline,
  EditOutline, ExperimentOutline, ExportOutline, EyeOutline, EyeInvisibleOutline,
  FieldNumberOutline, FileTextOutline, FilterOutline, FolderOutline,
  HistoryOutline, HolderOutline, ImportOutline, InfoCircleOutline, InfoOutline,
  LeftOutline, LineChartOutline, LinkOutline, LockOutline, LogoutOutline,
  MergeCellsOutline, MoreOutline, NodeExpandOutline, PercentageOutline, PlayCircleOutline, PlusOutline,
  QrcodeOutline, QuestionCircleOutline, ReloadOutline, RightOutline,
  SafetyCertificateOutline, SafetyCertificateFill, SaveOutline, ScissorOutline, SearchOutline,
  SettingOutline, SettingTwoTone,
  TableOutline, TagOutline, TeamOutline, ToolOutline, TrophyOutline,
  UploadOutline, UserOutline, UserAddOutline, WarningOutline,
];
